coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**"
